# action.yml
name: '[RecapTime.dev] Build Mkdocs site over Docker container'
description: 'Builds a Mkdocs site over a Docker container environment based on Alpine Linux.'
inputs:
  config:
    description: 'Path to Mkdocs config file'
    required: true
    default: 'mkdocs.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config }}
