name: Documentation

on:
  push:
    branches: ["main"]

jobs:
  meta:
    uses: ./.github/workflows/mkdocs-build.yml
    secrets: inherit
    with:
      config: mkdocs.yml
    permissions:
      pages: write
      id-token: write
      contents: read