name: Documentation

on:
  push:
    branches: ["main"]
    paths:
      - docs/**/*.md
      - docs/*.md
      - mkdocs.yml
      - .github/workflows/docs.yml
      - .github/workflows/mkdocs-build.yml

jobs:
  meta:
    uses: ./.github/workflows/mkdocs-build.yml
    secrets: inherit
    with:
      config: mkdocs.yml
      deploy-to: cf-pages
    permissions:
      pages: write
      id-token: write
      contents: read
      deployments: write
